apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ixt1
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0074-tenant/tkrw-pr712-0075-0074-app/devfile-sample-ixt1@sha256:81689ce37484443fe0d6ad85a7113aa0f0a288002ae2c9ad125b8e857ff0f2ca
        name: my-nodejs
        resources: {}
status: {}
